
## useradd roboshop
#Download the repo
#$ cd /home/roboshop
#$ curl -s -L -o /tmp/shipping.zip "https://github.com/roboshop-devops-project/shipping/archive/main.zip"
#$ unzip /tmp/shipping.zip
#$ mv shipping-main shipping
#$ cd shipping
#$ mvn clean package
#$ mv target/shipping-1.0.jar shipping.jar
#Update Servers IP address in /home/roboshop/shipping/systemd.service
#
#Copy the service file and start the service.
#
## mv /home/roboshop/shipping/systemd.service /etc/systemd/system/shipping.service
## systemctl daemon-reload
## systemctl start shipping
## systemctl enable shipping

- name: Install Maven
  yum:
    name: maven
    state: present

- name: Add Roboshop Application user
  ansible.builtin.user:
    name: roboshop