- name: Demo on variables
  hosts: all
  vars:
    URL: play.goggle.com
  tasks:
    - name: Print a variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
    - name: Print task variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.goggle.com
## when there is variable reference (calling variable), double quote it

- name: Demo on Inv variables
  hosts: all
  tasks:
    - name: Print a Inv variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
      vars:
        URL: inv.goggle.com

- name: Demo on File variables
  hosts: all
  vars_file:
    - vars.yml
  tasks:
    - name: Print a variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
