- name: Demo on variables
  hosts: all
  vars:
    URL: goggle.com
  tasks:
    - name: Print a variable
      debug:
        msg: "URL = {{URL}}"

## when there is variable reference (calling variable), double quote it