- name: Install a package
  hosts: all
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present

- name: Install a package
  hosts: all
  tasks:
    - name: Install nodejs
      ansible.builtin.yum:
        name: nodejs
        state: present