- name: Install a package
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present

- name: Install a package
  hosts: all
  become: yes
  ## here all tasks runs as root user
  tasks:
    - name: Install nodejs
      become: yes
      ## This makes only this task to run as a root user
      ansible.builtin.yum:
        name: nodejs
        state: present