- name: Roboshop Frontend Setup
  hosts: FRONTEND
  become: yes
  roles:
    - name: frontend

- name: Roboshop Mongodb Setup
  hosts: MONGODB
  become: yes
  roles:
    - name: mongodb

- name: Roboshop Catalogue Setup
  hosts: CATALOGUE
  become: yes
  roles:
    - name: catalogue

- name: Roboshop Redis Setup
  hosts: REDIS
  become: yes
  roles:
    - name: redis

- name: Roboshop User Setup
  hosts: USER
  become: yes
  roles:
    - name: user