- name: Setup MySQL Repo file
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  yum:
    name: [ "mysql-community-server", "MySQL-python" ]
    state: present

- name: Start MySQL Service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the default password
  community.mysql.mysql_query:
    query: show databases
    login_password: RoboShop@1
    login_user: root
  register: default_mysql_check
  ignore_errors: yes

#- name: Check the default password
#  shell: echo "show databases;" | mysql -uroot -pRoboShop@1
#  register: default_mysql_check
#  ignore_errors: yes

- name: pringt
  debug:
    msg: "{{default_mysql_check}}"

- name: Grab default password
  when: default_mysql_check.failed
  shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: out

- name: Reset MySQL Password
  shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';" | mysql --connect-expired-password -uroot -p${{out.stdout}}

#Run the following SQL commands to remove the password policy.
#> uninstall plugin validate_password;
#Setup Needed for Application.
#As per the architecture diagram, MySQL is needed by
#
#Shipping Service
#So we need to load that schema into the database, So those applications will detect them and run accordingly.
#
#To download schema, Use the following command
#
## curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
#Load the schema for Services.
#
## cd /tmp
## unzip mysql.zip
## cd mysql-main
# mysql -uroot -pRoboShop@1 <shipping.sql