- name: check node exporter does exist
  stat:
    path: /opt/node_exporter
  register: out

- name: Install Node Exporter
  when: not out.stat.exists
  block:
    - name: Download Prometheus Archive
      unarchive:
        src: "{{NODE_EXPORTER_URL}}"
        dest: /tmp
        remote_src: yes
#google search prometheus.io - download - node-exporter - 64-bit link
#google - unarchive module ansible

    - name: Copy Node exporter to /opt
      copy:
        src: /tmp/{{ NODE_EXPORTER_URL | split('/') | last | regex_replace('.tar.gz', '') }}/
        dest: /opt/node_exporter/
        remote_src: yes

- name: Setup Node Exporter service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start Node Exporter service
  systemd:
    name: node_exporter
    state: started