- name: check node exporter does exist
  stat:
    path: /opt/node_exporter
  register: out

- name: Install Node Exporter
  when: not out.stat.exists
  block:
    - name: Download Prometheus Archive
      unarchive:
        src: "{{NODE_EXPORTER_URL}}"
        dest: /tmp
        remote_src: yes
#google search prometheus.io - download - node-exporter - 64-bit link
#google - unarchive module ansible

    - name: Copy Node exporter to /opt
      copy:
        src: /tmp/{{ NODE_EXPORTER_URL | split('/') | last | regex_replace('.tar.gz', '') }}
        dest: /opt/node_exporter
        remote_src: yes




#URL=$(curl -L -s https://prometheus.io/download/  | grep tar | grep node_exporter | grep linux-amd64  | sed -e "s|>| |g" -e 's|<| |g' -e 's|"| |g' |xargs -n1 | grep ^http)

#FILENAME=$(echo $URL | awk -F / '{print $NF}')
#DIRNAME=$(echo $FILENAME | sed -e 's/.tar.gz//')

#cd /opt
#curl -s -L -O $URL
#tar -xf $FILENAME
#rm -f $FILENAME
#mv $DIRNAME node_exporter

#curl -s https://raw.githubusercontent.com/linuxautomations/labautomation/master/tools/prometheus-node-exporter/prometheus.service >/etc/systemd/system/node_exporter.service
#systemctl enable node_exporter
#systemctl start node_exporter
